routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::get('email', function() {

//     return new App\Mail\LoginCredentials(App\User::first(), 'asd123');
// });


Route::get('/', 'PagesController@home')->name('pages.home');
Route::get('nosotros', 'PagesController@about')->name('pages.about');
Route::get('archivo', 'PagesController@archive')->name('pages.archive');
Route::get('contacto', 'PagesController@contact')->name('pages.contact');
Route::get('staticpage', 'StaticPage@show')->name('staticpage.show');



Route::get('blog/{post}', 'PostsController@show')->name('posts.show');
Route::get('categorias/{category}', 'CategoriesController@show')->name('categories.show');
Route::get('tags/{tag}', 'TagsController@show')->name('tags.show');


Route::get('login/{socialNetwork}', 'SocialLoginController@redirectToSocialNetwork')->name('login.social')->middleware('guest');
Route::get('login/{SocialNetwork}/callback', 'SocialLoginController@handleSocialNetworkCallback')->middleware('guest');

//Métodos con el prefijo Admin

Route::group(['prefix' => 'admin', 
    'namespace' => 'Admin', 
    'middleware' => 'auth'], 
    function() {
        //rutas de administración
    Route::get('/','AdminController@index')->name('dashboard');


    Route::resource('media', 'MediaController', ['except' => 'show', 'as' => 'admin']);

    Route::resource('contacts', 'ContactController', ['except' => 'show', 'as' => 'admin']);
    Route::resource('page', 'PageController', ['except' => '', 'as' => 'admin']);
    Route::resource('projects', 'ProjectController', ['except' => 'show', 'as' => 'admin']);
    Route::get('procjects/goback', 'ProjectController@goback')->name('admin.projects.goback');


    Route::resource('setting', 'SettingController', ['except' => '', 'as' => 'admin']);
    Route::resource('posts', 'PostsController', ['except' => 'show', 'as' => 'admin']);
    Route::resource('users', 'UsersController', [ 'as' => 'admin']);
    Route::resource('roles', 'RolesController', ['except' => 'show', 'as' => 'admin']);
    Route::resource('permissions', 'PermissionsController', ['only' => ['index', 'edit', 'update'], 'as' => 'admin']);

    Route::middleware('role:Admin')->put('users/{user}/roles', 'UsersRolesController@update')->name('admin.users.roles.update');

    Route::middleware('role:Admin')->put('users/{user}/permissions', 'UsersPermissionController@update')->name('admin.users.permissions.update');


    Route::post('posts/{post}/photos', 'PhotosController@store')->name('admin.posts.photos.store');     
    Route::delete('photos/{photo}', 'PhotosController@destroy')->name('admin.photos.destroy');

    Route::post('projects/{project}/projectphotos', 'ProjectPhotosController@store')->name('admin.projectphotos.projectphotos.store'); 

    Route::post('projects/{project}/projectheader', 'ProjectPhotosController@header')->name('admin.projectphotos.projectphotos.header'); 

    Route::delete('projectphotos/{projectphoto}', 'ProjectPhotosController@destroy')->name('admin.projectphotos.destroy');     
});


//Quitar para desactivar registro
Auth::routes();
        // Authentication Routes...
        Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
        Route::post('login', 'Auth\LoginController@login');
        Route::post('logout', 'Auth\LoginController@logout')->name('logout');

        Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
        Route::post('register', 'Auth\RegisterController@register');

        Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
        Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

app/Http/Controllers/Admin/RolesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\Http\Requests\SaveRolesRequest;


class RolesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
         $this->authorize('view', new Role);

        return view('admin.roles.index', [
            'roles' => Role::all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', $role = new Role);

        return view('admin.roles.create', [

                'permissions' => Permission::pluck('name', 'id'),
                'role' => $role,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SaveRolesRequest $request)
    {

         $this->authorize('create', new Role);

    
        $role = Role::create($request->validated());


        if($request->has('permissions')){
        
        $role->givePermissionTo($request->premissions);

      }

      return redirect()->route('admin.roles.index')->withFlash('El rol fue creado correctamente');
      
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {

        $this->authorize('update', $role);


        return view('admin.roles.edit', [

            'role' => $role,
            'permissions' => Permission::pluck('name', 'id'),

        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(SaveRolesRequest $request, Role $role)
    {

         $role->update($request->validated());

            $role->permissions()->detach();

         if ($request->has('permissions'))
         {
             $role->givePermissionTo($request->permissions);
        }
            return redirect()->route('admin.roles.edit', $role)->withFlash('El rol fue actualizado correctamente');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function destroy(Role $role)

    {
         $this->authorize('delete', $role);


         $role->delete();

         return redirect()->route('admin.roles.index')->withFlash('El role fue eliminado');
    }
}

resources/views/admin/roles/checkboxes.blade.php
@foreach($roles as $role)

    	<div class="checkbox">
    		<label>
    			<input name="roles[]" type="checkbox" value="{{$role->name}}" 
    			{{$user->roles->contains($role->id) ? 'checked' : ''}}>
    			{{$role->name}}<br>
                <small class="text-muted">{{$role->permissions->pluck('name')->implode(', ')}}</small>
    		</label>
    	</div>
    	@endforeach

resources/views/admin/roles/create.blade.php
@extends('admin.layout')
@section('content')

<div class="row">
	
	<div class="col-md-12">
	<div class="card card-primary">
    	<div class="card-header"></div>
    	<div class="card-body">   
    	<h3 class="box-title">Crear Rol</h3>
    	<hr>
        @include('partials.validationmessages')
    	<form method="POST" action="{{route('admin.roles.store')}}">
    		       @include('admin.roles.form')
    		<button class="btn btn-primary btn-block">
    				Crear Rol
    		</button>
    		
    	</form>
    	</div>      

 	</div>
</div>
</div>

@endsection

resources/views/admin/roles/edit.blade.php
@extends('admin.layout')
@section('content')

<div class="row">
	
	<div class="col-md-12">
	<div class="card card-primary">
    	<div class="card-header"></div>
    	<div class="card-body">   
    	<h3 class="box-title">Editar Rol</h3>
    	<hr>
        @include('partials.validationmessages')
    	<form method="POST" action="{{route('admin.roles.update', $role)}}">
    		{{method_field('PUT')}}

            @include('admin.roles.form')

    		<button class="btn btn-primary btn-block">
    				Actualizar Rol
    		</button>
    		
    	</form>
    	</div>      

 	</div>
</div>
</div>

@endsection

resources/views/admin/roles/form.blade.php
            {{csrf_field()}} 
    		<div class="form-group">
    			<label for="name">
    				Identificador:
    			</label>
                @if($role->exists)
    			<input value="{{$role->name}}" class="form-control" disabled>
                @else
                <input name="name" value="{{old('name', $role->name)}}" class="form-control">
                @endif
    		</div>

            <div class="form-group">
                <label for="display_name">
                    Nombre:
                </label>
                <input name="display_name" value="{{old('display_name', $role->display_name)}}" class="form-control">
            </div>
		<div class="row">
			<div class="form-group col-md-6">
    			<label>Permisos</label>
    			@include('admin.permissions.checkboxes', ['model' => $role])
    		</div>    		
    	</div>

resources/views/admin/roles/index.blade.php
@extends('admin.layout')
@section('header')
      <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Roles</h1>
            <small>Listado</small>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Inicio</a></li>
              <li class="breadcrumb-item active">Roles</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
@stop
@section('content')
          <div class="card">
            <div class="card-header" style="vertical-align:  middle;">
              <h3 class="card-title" style="vertical-align:  middle;">Usuarios</h3>
<!-- Button trigger modal -->
@can('create', $roles->first())
<a href="{{route('admin.roles.create')}}" class="btn btn-primary float-right">
+ Crear Rol
</a>
@endcan
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="roles-table" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>ID</th>
                  <th>Identificador</th>
                  <th>Nombre</th>
                  <th>Permisos</th>
                  <th>Acciones</th>
                </tr>
                </thead>
                <tbody>
                	@forelse($roles as $role)
               <tr>
                 <td>{{$role->id}}</td>
                  <td>{{$role->name}}</td>
                  <td>{{$role->display_name}}</td>
                  <td>{{$role->permissions->pluck('display_name')->implode(', ')}}</td>
                  <td>

                    @can('update' , $role)
                  	<a class="btn btn-info btn-sm" href="{{route('admin.roles.edit', $role)}}"><i class="fas fa-pencil-alt"></i></a>
                    @endcan 
                    @if($role->id !== 1)
                    @can('delete' , $role)
                    <form method="POST" action="{{route('admin.roles.destroy', $role)}}" style="display: inline;"> 
                      {{ csrf_field() }} {{method_field('DELETE')}}
                      
                    <button class="btn btn-danger btn-sm" href="" onclick="return confirm('Estás Seguro de Querer Eliminar Este Rol?')"><i class="fas fa-times"></i></button>

                    </form>
                    @endcan
                      
                    @endif

                  </td>

                   </tr>
                	@empty
                	<tr>
                		<td>No hay datos para mostrar</td>
                	</tr>
                	@endforelse
                </tbody>

              </table>
            </div>
            <!-- /.card-body -->
          </div>
@endsection



@push('styles')
    <!-- DataTables -->
  <link rel="stylesheet" href="/adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
@endpush

@push('scripts')
<!-- DataTables -->
<script src="/adminlte/plugins/datatables/jquery.dataTables.js"></script>
<script src="/adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>


<script>
  $(function () {
    $("#example1").DataTable();
    $('#roles-table').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
    });
  });
</script>




@endpush