routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::get('email', function() {

//     return new App\Mail\LoginCredentials(App\User::first(), 'asd123');
// });


Route::get('/', 'PagesController@home')->name('pages.home');
Route::get('nosotros', 'PagesController@about')->name('pages.about');
Route::get('archivo', 'PagesController@archive')->name('pages.archive');
Route::get('contacto', 'PagesController@contact')->name('pages.contact');
Route::get('staticpage', 'StaticPage@show')->name('staticpage.show');



Route::get('blog/{post}', 'PostsController@show')->name('posts.show');
Route::get('categorias/{category}', 'CategoriesController@show')->name('categories.show');
Route::get('tags/{tag}', 'TagsController@show')->name('tags.show');


Route::get('login/{socialNetwork}', 'SocialLoginController@redirectToSocialNetwork')->name('login.social')->middleware('guest');
Route::get('login/{SocialNetwork}/callback', 'SocialLoginController@handleSocialNetworkCallback')->middleware('guest');

//Métodos con el prefijo Admin

Route::group(['prefix' => 'admin', 
    'namespace' => 'Admin', 
    'middleware' => 'auth'], 
    function() {
        //rutas de administración
    Route::get('/','AdminController@index')->name('dashboard');


    Route::resource('media', 'MediaController', ['except' => 'show', 'as' => 'admin']);

    Route::resource('contacts', 'ContactController', ['except' => 'show', 'as' => 'admin']);
    Route::resource('page', 'PageController', ['except' => '', 'as' => 'admin']);
    Route::resource('projects', 'ProjectController', ['except' => 'show', 'as' => 'admin']);
    Route::get('procjects/goback', 'ProjectController@goback')->name('admin.projects.goback');


    Route::resource('setting', 'SettingController', ['except' => '', 'as' => 'admin']);
    Route::resource('posts', 'PostsController', ['except' => 'show', 'as' => 'admin']);
    Route::resource('users', 'UsersController', [ 'as' => 'admin']);
    Route::resource('roles', 'RolesController', ['except' => 'show', 'as' => 'admin']);
    Route::resource('permissions', 'PermissionsController', ['only' => ['index', 'edit', 'update'], 'as' => 'admin']);

    Route::middleware('role:Admin')->put('users/{user}/roles', 'UsersRolesController@update')->name('admin.users.roles.update');

    Route::middleware('role:Admin')->put('users/{user}/permissions', 'UsersPermissionController@update')->name('admin.users.permissions.update');


    Route::post('posts/{post}/photos', 'PhotosController@store')->name('admin.posts.photos.store');     
    Route::delete('photos/{photo}', 'PhotosController@destroy')->name('admin.photos.destroy');

    Route::post('projects/{project}/projectphotos', 'ProjectPhotosController@store')->name('admin.projectphotos.projectphotos.store'); 

    Route::post('projects/{project}/projectheader', 'ProjectPhotosController@header')->name('admin.projectphotos.projectphotos.header'); 

    Route::delete('projectphotos/{projectphoto}', 'ProjectPhotosController@destroy')->name('admin.projectphotos.destroy');     
});


//Quitar para desactivar registro
Auth::routes();
        // Authentication Routes...
        Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
        Route::post('login', 'Auth\LoginController@login');
        Route::post('logout', 'Auth\LoginController@logout')->name('logout');

        Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
        Route::post('register', 'Auth\RegisterController@register');

        Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
        Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

app/User.php
<?php

namespace App;

use Spatie\Permission\Traits\HasRoles;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;


class User extends Authenticatable
{
    use Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function posts(){


        return $this->hasMany(Post::class);

    }

    public function setPasswordAttribute ($password) {


        $this->attributes['password'] = bcrypt($password);
    }

    public function scopeAllowed ($query) {


        
        if(auth()->user()->can('view', $this))
        {

            return $query;

        }

        else
        {

            return $query->where('id', auth()->id());

        }

    }

    public function getRoleDisplayNames(){


    return $this->roles->pluck('display_name')->implode(', ');        

    }

    public function profiles() 
    {

        return $this->hasMany(SocialProfile::class);

    }

    public function getAvatarAttribute() {

        return optional ($this->profiles->last())->avatar ?? url('img/account.png');

    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use App\Events\UserWasCreated;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\Http\Requests\UpdateUserRequest;


class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::get();

        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $user = new User;
        $this->authorize('create', $user);


        $roles = Role::with('permissions')->get();
        $permissions = Permission::pluck('name', 'id');
        return view('admin.users.create', compact('user', 'roles', 'permissions'));    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->authorize('create', new User);

        $data = $request->validate([
        'name' => ['required', 'string', 'max:255'],
        'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
        ]);

        $data['password'] = str_random(8);

        $user = User::create($data);

        if($request->filled('roles'))
        {
        
        $user->assignRole($request->roles);

        }
        
     if($request->filled('permissions'))
        {
        $user->givePermissionto($request->permissions);
        }
        

        UserWasCreated::dispatch($user, $data['password']);

        return redirect()->route('admin.users.index')->withFlash('El Usuario Ha Sido Creado');



    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
            $this->authorize('view', $user);

        return view('admin.users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $this->authorize('update', $user);

        $roles = Role::with('permissions')->get();
        $permissions = Permission::pluck('name', 'id');
        return view('admin.users.edit', compact('user', 'roles', 'permissions'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request, User $user)
    {

    $this->authorize('update', $user);
       $user->update($request->validated());

       return redirect()->route('admin.users.edit', $user)->withFlash('Usuario Actualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $this->authorize('delete', $user);
        $user->delete();
        return redirect()->route('admin.users.index')->withFlash('Usuario Eliminado');

    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layout')
@section('content')

<h1>Crear Usuario</h1>

<div class="row">
	
	<div class="col-md-12">
	<div class="card card-primary">
    	<div class="card-header"></div>
    	<div class="card-body">   
    	<h3 class="box-title">Datos de Usuario</h3>
    	<hr>
    	@if ($errors->any())
    	<ul class="list-group">
        @include('partials.validationmessages') 
    	</ul>
    	@endif
    	<form method="POST" action="{{route('admin.users.store')}}">
    		{{csrf_field()}}
    		<div class="form-group">
    			<label for="name">
    				Nombre:
    			</label>
    			<input name="name" value="{{old('name')}}" class="form-control">
    		</div>
    		<div class="form-group">
    			<label for="email">
    				email:
    			</label>
    			<input name="email" value="{{old('email')}}" class="form-control">
    		</div>
		<div class="row">
    		<div class="form-group col-md-6">
    			<label>Roles</label>
    			@include('admin.roles.checkboxes')
    		</div>

			<div class="form-group col-md-6">
    			<label>Permisos</label>
    			@include('admin.permissions.checkboxes', ['model' => $user])
    		</div>    		
    	</div>

    		<div class="form-group">
    	<span class="help-block"> La contraseña será generada y enviada al nuevo usuario por email</span>
    		</div>
    		<button class="btn btn-primary btn-block">
    				Crear Usuario
    		</button>
    		
    	</form>
    	</div>      

 	</div>
</div>
</div>

@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layout')
@section('content')

<div class="row">
		
<div class="col-md-7">
	<div class="card card-primary">
    	<div class="card-header"></div>
    	<div class="card-body">   
    	<h3 class="box-title">Datos de Usuario</h3>
    	<hr>
        @include('partials.validationmessages')
    	<form method="POST" action="{{route('admin.users.update', $user)}}">
    		{{csrf_field()}} {{method_field('PUT')}}
    		<div class="form-group">
    			<label for="name">
    				Nombre:
    			</label>
    			<input name="name" value="{{old('name', $user->name)}}" class="form-control">
    		</div>
    		<div class="form-group">
    			<label for="email">
    				email:
    			</label>
    			<input name="email" value="{{old('email', $user->email)}}" class="form-control">
    		</div>

    		    <div class="form-group">
    			<label for="password">
    				Contraseña:
    			</label>
    			<input name="password" class="form-control" type="password" placeholder="Contraseña">
    			    			<span class="help-block"> Dejar en blanco si no quieres cambiar tu contraseña </span>
    		</div>

    		    		    <div class="form-group">
    			<label for="password_confirmation">
    				Confirmar Contraseña:
    			</label>
    			<input name="password_confirmation" class="form-control" type="password" placeholder="Repite la Contraseña">

    		</div>

    		<button class="btn btn-primary btn-block">
    				Actualizar Usuario
    		</button>
    		
    	</form>
    	</div>      

 	</div>
</div>


<div class="col-md-5">
	<div class="card card-primary">
    	<div class="card-header"></div>
    	<div class="card-body">   
    	<h3 class="box-title">Roles</h3>
    	<hr>
        @role('Admin')
    	<form method="POST" action="{{route('admin.users.roles.update', $user)}}">
    		{{csrf_field()}}  {{method_field('PUT')}}
    	@include('admin.roles.checkboxes')
    	<button class="btn btn-primary btn-block"> Actualizar Roles </button>
    	</form>
        @else

        <ul class="list-group">

            @forelse($user->roles as $role)
            <li class="list-group-item">
                {{$role->name}}
            </li>
            @empty
            <li class="list-group-item">No hay roles para mostrar</li>
            @endforelse
        </ul>
        @endrole
    	</div>      

 	</div>

	<div class="card card-primary">
    	<div class="card-header"></div>
    	<div class="card-body">   
    	<h3 class="box-title">Permisos</h3>
    	<hr>
        @role('Admin')
    	<form method="POST" action="{{route('admin.users.permissions.update', $user)}}">
    		{{csrf_field()}}  {{method_field('PUT')}}
    	@include('admin.permissions.checkboxes', ['model' => $user])
    	<button class="btn btn-primary btn-block"> Actualizar Permisos </button>
    	</form>
        @else
                <ul class="list-group">

            @forelse($user->permissions as $permission)
            <li class="list-group-item">
                {{$permission->name}}
            </li>
            @empty
            <li class="list-group-item">No hay permisos para mostrar</li>
            @endforelse
        </ul>
        @endrole
    	</div>      

 	</div>
</div>


</div>
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layout')
@section('header')
      <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Usuarios</h1>
            <small>Listado</small>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Inicio</a></li>
              <li class="breadcrumb-item active">Usuarios</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
@stop
@section('content')
          <div class="card">
            <div class="card-header" style="vertical-align:  middle;">
              <h3 class="card-title" style="vertical-align:  middle;">Usuarios</h3>
<!-- Button trigger modal -->
@can('create', $users->first())
  <a href="{{route('admin.users.create')}}" class="btn btn-primary float-right">
  + Crear Usuario
  </a>
@endcan
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="users-table" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>ID</th>
                  <th>Nombre</th>
                  <th>Email</th>
                  <th>Roles</th>
                  <th>Acciones</th>
                </tr>
                </thead>
                <tbody>
                	@forelse($users as $user)
                  @can('view', $user)
               <tr>
                 <td>{{$user->id}}</td>
                  <td>{{$user->name}}</td>
                  <td>{{$user->email}}</td>
                  <td>{{$user->getRoleNames()->implode(', ')}}</td>
                  <td>
                    @can('view', $user)
                    <a class="btn btn-default btn-sm" href="{{route('admin.users.show', $user)}}" target="_self"><i class="fas fa-eye"></i></a>
                    @endcan
                  @can('view', $user)
                  	<a class="btn btn-info btn-sm" href="{{route('admin.users.edit', $user)}}"><i class="fas fa-pencil-alt"></i></a>
                    @endcan

                    @can('delete', $user)
                    <form method="POST" action="{{route('admin.users.destroy', $user)}}" style="display: inline;"> 
                      {{ csrf_field() }} {{method_field('DELETE')}}
                      
                    <button class="btn btn-danger btn-sm" href="" onclick="return confirm('Estás Seguro de Querer Eliminar Este Usuario?')"><i class="fas fa-times"></i></button>

                    </form>
                    @endcan

                  </td>

                   </tr>
                   @endcan
                	@empty
                	<tr>
                		<td>No hay datos para mostrar</td>
                	</tr>
                	@endforelse
                </tbody>

              </table>
            </div>
            <!-- /.card-body -->
          </div>
@endsection



@push('styles')
    <!-- DataTables -->
  <link rel="stylesheet" href="/adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
@endpush

@push('scripts')
<!-- DataTables -->
<script src="/adminlte/plugins/datatables/jquery.dataTables.js"></script>
<script src="/adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>


<script>
  $(function () {
    $("#example1").DataTable();
    $('#users-table').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
    });
  });
</script>




@endpush

resources/views/admin/users/show.blade.php
@extends('admin.layout')
@section('content')

	<div class="row">
		<div class="col-md-3">
<div class="card card-primary card-outline">
              <div class="card-body box-profile">
                <div class="text-center">
                  <img class="profile-user-img img-fluid img-circle" src="{{optional(Auth::user())->avatar}}" alt="{{$user->name}}" width="128">
                </div>

                <h3 class="profile-username text-center">{{$user->name}}</h3>

                <p class="text-muted text-center">{{$user->getRoleNames()->implode(', ')}}</p>

                <ul class="list-group list-group-unbordered mb-3">
                  <li class="list-group-item">
                    <b>email</b> <br><a class="float-left">{{$user->email}}</a>
                  </li>
                  <li class="list-group-item">
                    <b>Publicaciones</b> <a class="float-right">{{$user->posts->count()}}</a>
                  </li>
                  <li class="list-group-item">
                    <b>Roles</b> <a class="float-right">{{$user->getRoleNames()->implode(', ')}}</a>
                  </li>
                </ul>

                <a href="{{route('admin.users.edit', $user)}}" class="btn btn-primary btn-block"><b>Editar</b></a>
              </div>
              <!-- /.card-body -->
            </div>
		</div>
		<div class="col-md-3">
			<div class="card card-primary card-outline">
				 <div class="card-body">
				 	<h3 class="box-title">Publicaciones</h3>
				 </div>
				 <div class="card-body">
				 	
				 	@forelse($user->posts as $post)
  <ul class="list-group list-group-unbordered mb-3">
                  <li class="list-group-item">
				 	<a href="{{route('posts.show', $post)}}" target="_blank">
				 		<strong> {{$post->title}}</strong>
				 		</a><br>
				 		<small class="text-muted">Publicado el {{$post->published_at->format('d/m/Y')}}</small>
						<p class="text-muted"> {{$post->excerpt}} </p>
						@unless($loop->last)
					
						@endunless
</li>				
	@empty
	<small class="text-muted"> No hay publicaciones</small>
					@endforelse
				 	

				 </div>
			</div>
		</div>
		<div class="col-md-3">
						<div class="card card-primary card-outline">
				 <div class="card-body">
				 	<h3 class="box-title">Permisos</h3>
				 </div>
				 <div class="card-body">
				 	
				 	@forelse($user->roles as $role)
				 			 
				 		<strong> {{$role->name}}</strong>
				 						 		<br>
				 		@if($role->permissions->count())
				 		<small class="text-muted">Permisos: {{$role->permissions->pluck('name')->implode(', ')}}</small>
						@unless($loop->last)
						<hr>
						@endif
						@endunless

					@empty
	<small class="text-muted"> No hay roles asociados</small>
					@endforelse
				 	

				 </div>
			</div>
		</div>
		<div class="col-md-3">
						<div class="card card-primary card-outline">
				 <div class="card-body">
				 	<h3 class="box-title">Permisos Adicionales</h3>
				 </div>
				 <div class="card-body">
				 	
				 	@forelse($user->permissions as $permission)
				 		<strong> {{$permission->name}}</strong>
						@unless($loop->last)
						<hr>
						@endunless

					@empty
	<small class="text-muted"> No hay permisos adicionales asignados</small>
					@endforelse
				 	

				 </div>
			</div>
		</div>
	</div>

@endsection