routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::get('email', function() {

//     return new App\Mail\LoginCredentials(App\User::first(), 'asd123');
// });


Route::get('/', 'PagesController@home')->name('pages.home');
Route::get('nosotros', 'PagesController@about')->name('pages.about');
Route::get('archivo', 'PagesController@archive')->name('pages.archive');
Route::get('contacto', 'PagesController@contact')->name('pages.contact');
Route::get('staticpage', 'StaticPage@show')->name('staticpage.show');



Route::get('blog/{post}', 'PostsController@show')->name('posts.show');
Route::get('categorias/{category}', 'CategoriesController@show')->name('categories.show');
Route::get('tags/{tag}', 'TagsController@show')->name('tags.show');


Route::get('login/{socialNetwork}', 'SocialLoginController@redirectToSocialNetwork')->name('login.social')->middleware('guest');
Route::get('login/{SocialNetwork}/callback', 'SocialLoginController@handleSocialNetworkCallback')->middleware('guest');

//Métodos con el prefijo Admin

Route::group(['prefix' => 'admin', 
    'namespace' => 'Admin', 
    'middleware' => 'auth'], 
    function() {
        //rutas de administración
    Route::get('/','AdminController@index')->name('dashboard');


    Route::resource('media', 'MediaController', ['except' => 'show', 'as' => 'admin']);

    Route::resource('contacts', 'ContactController', ['except' => 'show', 'as' => 'admin']);
    Route::resource('page', 'PageController', ['except' => '', 'as' => 'admin']);
    Route::resource('projects', 'ProjectController', ['except' => 'show', 'as' => 'admin']);
    Route::get('procjects/goback', 'ProjectController@goback')->name('admin.projects.goback');


    Route::resource('setting', 'SettingController', ['except' => '', 'as' => 'admin']);
    Route::resource('posts', 'PostsController', ['except' => 'show', 'as' => 'admin']);
    Route::resource('users', 'UsersController', [ 'as' => 'admin']);
    Route::resource('roles', 'RolesController', ['except' => 'show', 'as' => 'admin']);
    Route::resource('permissions', 'PermissionsController', ['only' => ['index', 'edit', 'update'], 'as' => 'admin']);

    Route::middleware('role:Admin')->put('users/{user}/roles', 'UsersRolesController@update')->name('admin.users.roles.update');

    Route::middleware('role:Admin')->put('users/{user}/permissions', 'UsersPermissionController@update')->name('admin.users.permissions.update');


    Route::post('posts/{post}/photos', 'PhotosController@store')->name('admin.posts.photos.store');     
    Route::delete('photos/{photo}', 'PhotosController@destroy')->name('admin.photos.destroy');

    Route::post('projects/{project}/projectphotos', 'ProjectPhotosController@store')->name('admin.projectphotos.projectphotos.store'); 

    Route::post('projects/{project}/projectheader', 'ProjectPhotosController@header')->name('admin.projectphotos.projectphotos.header'); 

    Route::delete('projectphotos/{projectphoto}', 'ProjectPhotosController@destroy')->name('admin.projectphotos.destroy');     
});


//Quitar para desactivar registro
Auth::routes();
        // Authentication Routes...
        Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
        Route::post('login', 'Auth\LoginController@login');
        Route::post('logout', 'Auth\LoginController@logout')->name('logout');

        Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
        Route::post('register', 'Auth\RegisterController@register');

        Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
        Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

resources/views/admin/partials/nav.blade.php
<!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->

            <li class="nav-item">
            <a href="{{route('dashboard')}}" class= "nav-link {{setActiveRoute('dashboard')}}">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Panel de Control
              </p>
            </a>
          </li>

<!-- Inicia Blog-->          
          <li class="nav-item has-treeview  {{setActiveTreeview('admin.posts.index')}}">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-newspaper"></i>
              <p>
                Blog
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                  <a href="{{route('admin.posts.index')}}" class="nav-link {{setActiveRoute('admin.posts.index')}}">
                  <i class="far fa-eye nav-icon"></i>
                  <p>Ver Todos los Post</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="#" data-toggle="modal" data-target="#exampleModalLong" class="nav-link">
                  <i class="fas fa-pencil-alt nav-icon"></i>
                  <p>Crear Post</p>
                </a>
              </li>
            </ul>
          </li>
<!-- Termina Blog-->    
<!-- Inicia Portfolio-->
          <li class="nav-item has-treeview  {{setActiveTreeview('admin.projects.index')}}">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-briefcase"></i>
              <p>
                Proyectos
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                  <a href="{{route('admin.projects.index')}}" class="nav-link {{setActiveRoute('admin.projects.index')}}">
                  <i class="far fa-eye nav-icon"></i>
                  <p>Ver Todos los Proyectos</p>
                </a>
              </li>
            </ul>
          </li>

<!-- Termina Portfolio-->

<!-- Inicia Páginas Estáticas-->
          <li class="nav-item has-treeview  {{setActiveTreeview('admin.page.index')}}">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-scroll"></i>
              <p>
                Páginas
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                  <a href="{{route('admin.page.index')}}" class="nav-link {{setActiveRoute('admin.page.index')}}">
                  <i class="far fa-eye nav-icon"></i>
                  <p>Ver Todas las páginas</p>
                </a>
              </li>

            </ul>
          </li>

<!-- Termina Páginas Estáticas-->   

<!-- Inicia Medios -->


          <li class="nav-item has-treeview  {{setActiveTreeview('admin.media.index')}}">
            <a href="#" class="nav-link">
              <i class="nav-icon far fa-image"></i>
              <p>
                Imágenes
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                  <a href="{{route('admin.media.index')}}" class="nav-link {{setActiveRoute('admin.media.index')}}">
                  <i class="far fa-eye nav-icon"></i>
                  <p>Ver Todas las imágenes</p>
                </a>
              </li>

            </ul>
          </li>


<!-- Termina Medios -->

<!-- Inicia Contacto-->
          <li class="nav-item has-treeview  {{setActiveTreeview('admin.contacts.index')}}">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-address-card"></i>
              <p>
                Contacto
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                  <a href="{{route('admin.contacts.index')}}" class="nav-link {{setActiveRoute('admin.contacts.index')}}">
                  <i class="far fa-eye nav-icon"></i>
                  <p>Ver Todas los registros</p>
                </a>
              </li>
            </ul>
          </li>

<!-- Termina Contacto-->   





          @can('view', new App\User)
          <li class="nav-item has-treeview  {{setActiveTreeview(['admin.users.index', 'admin.users.create'])}}">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-users"></i>
              <p>
                Usuarios
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                  <a href="{{route('admin.users.index')}}" class="nav-link {{setActiveRoute('admin.users.index')}}">
                  <i class="far fa-user nav-icon"></i>
                  <p>Ver Todos los Usuarios</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{route('admin.users.create')}}" class="nav-link {{setActiveRoute('admin.users.create')}}">
                  <i class="fas fa-pencil-alt nav-icon"></i>
                  Crear Usuario
                </a>
              </li>
            </ul>
          </li>
          @else
          <li class="nav-item">
            <a href="{{route('admin.users.show', auth()->user())}}" class= "nav-link {{setActiveRoute([ 'admin.users.show', 'admin.users.edit'])}}">
              <i class="nav-icon fas fa-user-alt"></i>
              <p>
                Perfil
              </p>
            </a>
          </li>
          @endcan


<!-- Inicia Settings-->
 @can('view', new \Spatie\Permission\Models\Permission)
          <li class="nav-item has-treeview  {{setActiveTreeview('admin.setting.index')}}">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-cog"></i>
              <p>
                Configuración
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">

            <li class="nav-item">
            <a href="{{route('admin.setting.index')}}" class= "nav-link {{setActiveRoute(['admin.setting.index'])}}">
              <i class="nav-icon fas fa-pencil-alt"></i>
              <p>
                Configuración de Sitio
              </p>
            </a>
          </li>
         
            <li class="nav-item">
            <a href="{{route('admin.roles.index')}}" class= "nav-link {{setActiveRoute(['admin.roles.index', 'admin.roles.edit'])}}">
              <i class="nav-icon fas fa-pencil-alt"></i>
              <p>
                Roles
              </p>
            </a>
          </li>
          @endcan
          @can('view', new \Spatie\Permission\Models\Permission)
            <li class="nav-item">
            <a href="{{route('admin.permissions.index')}}" class= "nav-link {{setActiveRoute(['admin.permissions.index', 'admin.permissions.edit'])}}">
              <i class="nav-icon fas fa-pencil-alt"></i>
              <p>
                Permisos
              </p>
            </a>
          </li>
          @endcan
 
            </ul>
          </li>

<!-- Termina Settings-->   



        </ul>
      </nav>